config/routes.rb
TwitterForZombies::Application.routes.draw do
  resources :zombies do
    resources :tweets
  end

  

end

app/models/assignments.rb
class Assignments < ActiveRecord::Base
	belongs_to :zombie
	belongs_to :role
end

app/models/brain.rb
class Brain < ActiveRecord::Base
	belongs_to :zombie
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments, class_name: "Assignments"
	has_many :zombies, through: :assignments
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base

	after_save :decomp_change_notification, if: :decomp_changed?
	has_one :brain, dependent: :destroy
	has_many :assignments, class_name: "Assignments"
	has_many :tweets
	has_many :roles, through: :assignments
	before_save :decomposition_state


	scope :rotting, -> {where(decomp_state: "rotting")}
	scope :fresh, -> {where("age < 20")}
	scope :recent, -> {where("created_at desc").limit(3)}


	def decomposition_state
		self.decomp_state = "rotting" if age > 20 && age < 25 #reading variables doesn't need self
	end
	private
	def decomp_change_notification
		ZombieMailer.decomp_change.self.deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rotting_zombies_controller.rb
class RottingZombiesController < ApplicationController

	def index
		@rotting_zombies = Zombie.rotting.limit(5)
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :get_zombie
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = @zombie.tweets
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = @zombie.tweets.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = @zombie.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to [@zombie, @tweet], notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@zombie, @tweet] }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to [@zombie, @tweet], notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  def get_zombie
    @zombie = Zombie.find(params[:zombie_id])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.includes(:brain).all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @zombie }
      else
        format.html { render action: 'new' }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])
    
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age, :decomp_state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rotting_zombies_helper.rb
module RottingZombiesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterForZombies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for([@zombie, @tweet]) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_field :tweet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', [@zombie, @tweet] %> |
<%= link_to 'Back', zombie_tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet %></td>
        <td><%= link_to 'Show', [@zombie, tweet] %></td>
        <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
        <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', zombie_tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_zombie_tweet_path(@zombie, @tweet) %> |
<%= link_to 'Back', zombie_tweets_path %>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%=f.label :decomposition_state %>
    <%=f.select :decomp_state, ['fresh','rotting','stale'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Decompositon State</th>
      <th>Brain Flavour</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.decomp_state %></td>
        <td><%= zombie.brain.flavour %></td>
        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>